<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>HKmoviesShop</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <link rel="stylesheet" href="../assets/style/style.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">
    <link rel="stylesheet" href="../assets/style/addings.css">
    <link rel="stylesheet" href="style.css">
</head>

<body>
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-margin background">
            <div class="container-fluid">
                <a class="navbar-brand" href="../layout.phtml"><img src="../assets/images/logoDark-removebg.png" alt="" class="logo"></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="../index.php"><span class="material-symbols-outlined text-white">
                                    home
                                </span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#"><span class="material-symbols-outlined text-white">
                                    movie
                                </span></a>
                        </li>
                    </ul>
                    <div class="float-end d-flex info" style="margin-left: -12%;">
                        <div class="dropdown text-end">
                            <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                                <img src="<?= $_SESSION['avatar'] ?>" alt="mdo" width="32" height="32" class="rounded-circle">
                            </a>
                            <ul class="dropdown-menu text-small">
                                <li><a class="dropdown-item" href="#">Settings</a></li>
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li><a class="dropdown-item" href="../logout/">Sign out</a></li>
                            </ul>
                        </div>
                        <p><?= $_SESSION['username'] ?></p>
                    </div>
                </div>
            </div>
        </nav>
        <div class="main">
            <div class="row">
                <?php if (array_key_exists('msg', $_GET)) : ?>
                    <div class="alert alert-<?= $_GET['class'] ?>">
                        <?= $_GET['msg']; ?>
                    </div>
                <?php endif; ?>
            </div>
            <div class="d-flex align-items-start">
                <div class="nav flex-column nav-pills me-3" id="v-pills-tab" role="tablist" aria-orientation="vertical">
                    <button class="nav-link active" id="v-pills-home-tab" data-bs-toggle="pill" data-bs-target="#v-pills-home" type="button" role="tab" aria-controls="v-pills-home" aria-selected="true"><span class="material-symbols-outlined">
                            grid_view
                        </span></button>
                    <button class="nav-link" id="v-pills-profile-tab" data-bs-toggle="pill" data-bs-target="#v-pills-profile" type="button" role="tab" aria-controls="v-pills-profile" aria-selected="false"><span class="material-symbols-outlined">
                            pending
                        </span></button>
                    <button class="nav-link" id="v-pills-messages-tab" data-bs-toggle="pill" data-bs-target="#v-pills-messages" type="button" role="tab" aria-controls="v-pills-messages" aria-selected="false"><span class="material-symbols-outlined">
                            delete
                        </span></button>
                    <button class="nav-link" id="v-pills-employes-tab" data-bs-toggle="pill" data-bs-target="#v-pills-employes" type="button" role="tab" aria-controls="v-pills-employes" aria-selected="false"><span class="material-symbols-outlined">
                            badge
                        </span></button>
                </div>
                <div class="tab-content" id="v-pills-tabContent">
                    <div class="tab-pane fade show active tab-bg" id="v-pills-home" role="tabpanel" aria-labelledby="v-pills-home-tab" tabindex="0">
                        <div class="insights row">
                            <div class="sales col">
                                <span class="material-symbols-outlined">
                                    movie
                                </span>
                                <div class="middle">
                                    <div class="left">
                                        <h3>number of movies and shows</h3>
                                        <h1><?= products_number($db) ?></h1>
                                    </div>
                                    <div class="progress">
                                        <svg>
                                            <circle cx="38" cy="38" r="36"></circle>
                                        </svg>
                                        <div class="number">
                                            <p>50%</p>
                                        </div>
                                    </div>
                                </div>
                                <small class="text-muted">all time</small>
                            </div>
                            <div class="income col">
                                <span class="material-symbols-outlined">
                                    movie
                                </span>
                                <div class="middle ">
                                    <div class="left ">
                                        <h3>number of shows</h3>
                                        <h1><?=shows_number($db)?></h1>
                                    </div>
                                    <div class="progress ">
                                        <svg>
                                            <circle cx="38 " cy="38 " r="36 "></circle>
                                        </svg>
                                        <div class="number ">
                                            <p>15%</p>
                                        </div>
                                    </div>
                                </div>
                                <small class="text-muted">all time</small>
                            </div>
                            <div class="income col">
                                <span class="material-symbols-outlined">
                                    movie
                                </span>
                                <div class="middle ">
                                    <div class="left ">
                                        <h3>number of movies</h3>
                                        <h1><?= movies_number($db) ?></h1>
                                    </div>
                                    <div class="progress ">
                                        <svg>
                                            <circle cx="38 " cy="38 " r="36 "></circle>
                                        </svg>
                                        <div class="number ">
                                            <p>15%</p>
                                        </div>
                                    </div>
                                </div>
                                <small class="text-muted">all time</small>
                            </div>
                        </div>
                    </div>
                    <div class="tab-pane fade tab-bg" id="v-pills-profile" role="tabpanel" aria-labelledby="v-pills-profile-tab" tabindex="0">

                    </div>
                    <div class="tab-pane fade tab-bg" id="v-pills-messages" role="tabpanel" aria-labelledby="v-pills-messages-tab" tabindex="0">

                    </div>
                    <div class="tab-pane fade tab-bg" id="v-pills-employes" role="tabpanel" aria-labelledby="v-pills-employes-tab" tabindex="0">
                        <!-- <div class="row">
                            <?php foreach ($employes as $element) { ?>
                                <div class="card mb-3 col">
                                    <div class="row g-0">
                                        <div class="col-md-4">
                                            <img src="<?= $element['avatar'] ?>" class="img-fluid rounded-start" alt="employe image" />
                                        </div>
                                        <div class="col-md-8">
                                            <div class="card-body">
                                                <h5 class="card-title"><?= $element['username'] ?></h5>
                                                <p class="card-text">
                                                <p class="fw-light"><a href="<?= $element['email'] ?>"><?= $element['email'] ?></a></p>
                                                <p class="text-muted">working since : <?= $element['createdate'] ?></p>
                                                </p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            <?php } ?>
                        </div> -->
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col" style="margin-left: 20%;"><button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
                        Add Film
                    </button>
                </div>
                <div class="col flex-end" style="margin-left: 20%;"><button type="button" class="btn btn-primary" data-bs-target="#addshow" data-bs-toggle="modal">
                        Add tvshow
                    </button>
                </div>
                <!-- Modal -->
                <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h1 class="modal-title fs-5 text-center" id="exampleModalLabel">add movie</h1>
                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                                <form action="./index.php" method="POST" enctype="multipart/form-data">
                                    <div class="mb-3">
                                        <label for="movie_name" class="form-label">movie name</label>
                                        <input type="text" class="form-control" id="movie_name" name="movie_name" required>
                                    </div>
                                    <div class="mb-3">
                                        <label for="director" class="form-label">director</label>
                                        <input type="text" class="form-control" id="director" name="director" required>
                                    </div>
                                    <div class="mb-3">
                                        <label for="description" class="form-label">description</label>
                                        <input type="text" class="form-control" id="description" name="description" required>
                                    </div>
                                    <div class="mb-3">
                                        <label for="link" class="form-label">trailler link</label>
                                        <input type="text" class="form-control" id="link" name="link" required>
                                    </div>
                                    <div class="mb-3">
                                        <label for="length" class="form-label">length (in minutes)</label>
                                        <input type="number" class="form-control" id="length" name="length" required>
                                    </div>
                                    <div class="mb-3">
                                        <label for="poster" class="form-label">poster</label>
                                        <input type="file" class="form-control" id="poster" name="poster" required>
                                    </div>
                                    <div class="mb-3">
                                        <label for="genre" class="form-label">genre</label>
                                        <select name="idgenre" id="genre" class="form-select" required>
                                            <?php foreach ($genres as $element) : ?>
                                                <option value="<?= $element['idgenre'] ?>"><?= $element['namegenre'] ?></option>
                                            <?php endforeach; ?>
                                        </select>
                                    </div>
                                    <button type="submit" class="btn flex-end" style="background-color: #BA68C8;" name="add">Add movie</button>
                                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                </form>
                            </div>
                        </div>
                        <div class="modal-footer">
                        </div>
                    </div>
                </div>
                <div class="modal fade" id="addshow" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h1 class="modal-title fs-5 text-center" id="exampleModalLabel">add show</h1>
                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                                <form action="./index.php" method="POST" enctype="multipart/form-data">
                                    <div class="mb-3">
                                        <label for="show_name" class="form-label">tv show name</label>
                                        <input type="text" class="form-control" id="show_name" name="show_name" required>
                                    </div>
                                    <div class="mb-3">
                                        <label for="director" class="form-label">director</label>
                                        <input type="text" class="form-control" id="director" name="director" required>
                                    </div>
                                    <div class="mb-3">
                                        <label for="description" class="form-label">description</label>
                                        <input type="text" class="form-control" id="description" name="description" required>
                                    </div>
                                    <div class="mb-3">
                                        <label for="link" class="form-label">trailler link</label>
                                        <input type="text" class="form-control" id="link" name="link" required>
                                    </div>
                                    <div class="mb-3">
                                        <label for="poster" class="form-label">poster</label>
                                        <input type="file" class="form-control" id="poster" name="poster" required>
                                    </div>
                                    <div class="mb-3">
                                        <label for="genre" class="form-label">genre</label>
                                        <select name="idgenre" id="genre" class="form-select" required>
                                            <?php foreach ($genres as $element) : ?>
                                                <option value="<?= $element['idgenre'] ?>"><?= $element['namegenre'] ?></option>
                                            <?php endforeach; ?>
                                        </select>
                                    </div>
                                    <button type="submit" class="btn flex-end" style="background-color: #BA68C8;" name="add_show">Add show</button>
                                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                </form>
                            </div>
                        </div>
                        <div class="modal-footer">
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <h1 class="text-center">Added Movies</h1>
                    <?php foreach ($addedmovies as $element) : ?>
                        <div class="card row flex-center text-center" style="width: 20rem;margin-left:25%;">
                            <h5>movie name : <?= $element['movie_name'] ?></h5>
                            <h5>director : <?= $element['director'] ?></h5>
                            <h5>length : <?= calculer_taille($element['length'])['nbheures'] . ':' . calculer_taille($element['length'])['nbminutes']  ?></h5>
                            <h5>genre : <?php donner_genre($element['idgenre'], $db); ?></h5>
                            <div class="row">
                                <a href="index.php?id_delete_movie=<?= $element['idmovie'] ?>" class="col">
                                    <button class="btn btn-danger">delete</button>
                                </a>
                                <a href="#" class="col">
                                    <button class="btn btn-success">edit</button>
                                </a>
                            </div>
                        </div>
                        <hr>
                    <?php endforeach; ?>
                </div>
                <div class="col">
                    <h1 class="text-center">Added Shows</h1>
                    <?php foreach ($addedshows as $element) : ?>
                        <div class="card row flex-center text-center" style="width: 20rem;margin-left:25%;">
                            <h5>movie name : <?= $element['name'] ?></h5>
                            <h5>director : <?= $element['director'] ?></h5>
                            <h5>genre : <?php donner_genre($element['idgenre'], $db); ?></h5>
                            <div class="row">
                                <a href="index.php?id_delete_show=<?= $element['idtvshow'] ?>" class="col">
                                    <button class="btn btn-danger">delete</button>
                                </a>
                                <button class="btn btn-warning col">edit</button>
                            </div>
                        </div>
                        <hr>
                    <?php endforeach; ?>
                </div>
            </div>
        </div>
        <footer class="row row-cols-1 row-cols-sm-2 row-cols-md-5 py-5 border-top" style="color: white;">
            <div class="col mb-3">
                <a href="/" class="d-flex align-items-center mb-3 link-dark text-decoration-none">
                    <img src="../assets/images/logoDark-removebg.png" width="100" height="100">
                </a>
            </div>

            <div class="col mb-3">

            </div>

            <div class="col mb-3">
                <h5>Section</h5>
                <ul class="nav flex-column">
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-white">Home</a></li>
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-white">Features</a></li>
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-white">Pricing</a></li>
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-white">FAQs</a></li>
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-white">About</a></li>
                </ul>
            </div>
            <div class="col mb-3">
                <h5>Section</h5>
                <ul class="nav flex-column">
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-white">Home</a></li>
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-white">Features</a></li>
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-white">Pricing</a></li>
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-white">FAQs</a></li>
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-white">About</a></li>
                </ul>
            </div>
            <div class="col mb-3">
                <h5>socials</h5>
                <ul class="nav flex-column">
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-white"><i class="bi bi-facebook"></i></a></li>
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-white"> <i class="bi bi-instagram"></i></a></li>
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-white"> <i class="bi bi-github"></i></a></li>
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-white"><i class="bi bi-info-circle"></i></a></li>
                </ul>
            </div>
            <p class="text-muted">HKIMI MOHAMED AMIN &copy; 2022</p>
        </footer>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    <script src="../assets/script/script.js"></script>

</body>

</html>