<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>HKmoviesShop</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <link rel="stylesheet" href="./assets/style/style.css">
</head>
<body>
    <div class="container">
<nav class="navbar navbar-expand-lg bg-light navbar-margin">
  <div class="container-fluid">
    <a class="navbar-brand" href="#"><img src="./assets/images/logoLight.png" alt="" class="logo"></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#"><span class="material-symbols-outlined">
home
</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#"><span class="material-symbols-outlined">
movie
</span></a>
        </li>
        <li class="nav-item">
          <a href="#" class="nav-link"><span class="material-symbols-outlined">
badge
</span></a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          <span class="material-symbols-outlined">
manage_accounts
</span>
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#"><span class="material-symbols-outlined">
login
</span><span class="text-dropdown">login</span></a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#"><span class="material-symbols-outlined">
person_add
</span><span class="text-dropdown">Sign Up</span></a></li>
            <li><hr class="dropdown-divider"></li>
          </ul>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
  <div class="row">
  <div class="img-design col">
    <img src="./assets/images/Movie Night-bro.svg" alt="">
  </div>
  <div class="col text-design">
    <h1 class="text-center text-bold text-break text-capitalize fst-italic">wanna chill out and watch some movies ! come on sign up to HKmoviesShop and watch all your favourite movies and series</h1>
  </div>
  </div>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
</body>
</html>