<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>HKmoviesShop</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
  <link rel="stylesheet" href="./assets/style/style.css">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">
</head>

<body>
  <div class="container">
    <nav class="navbar navbar-expand-lg navbar-margin">
      <div class="container-fluid">
        <a class="navbar-brand" href="#"><img src="./assets/images/logoLight.png" alt="" class="logo"></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="#"><span class="material-symbols-outlined">
                  home
                </span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#"><span class="material-symbols-outlined">
                  movie
                </span></a>
            </li>
            <li class="nav-item">
              <a href="./applyjob/" class="nav-link"><span class="material-symbols-outlined">
                  badge
                </span></a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                <span class="material-symbols-outlined">
                  manage_accounts
                </span>
              </a>
              <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="#" data-bs-toggle="modal" data-bs-target="#exampleModal"><span class="material-symbols-outlined">
                      login
                    </span><span class="text-dropdown">login</span></a></li>
                <li>
                  <hr class="dropdown-divider">
                </li>
                <li><a class="dropdown-item" href="./signUp/"><span class="material-symbols-outlined">
                      person_add
                    </span><span class="text-dropdown">Sign Up</span></a></li>
                <li>
                  <hr class="dropdown-divider">
                </li>
              </ul>
            </li>
          </ul>
          <form class="d-flex" role="search">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          </form>
        </div>
      </div>
    </nav>
    <div class="main">
      <div class="row first-composant rounded">
        <div class="img-design col">
          <img src="./assets/images/Movie Night-bro.svg" alt="">
        </div>
        <div class="col text-design">
          <h1 class="text-center text-bold text-break text-capitalize fst-italic">wanna chill out and watch some movies ! come on sign up to HKmoviesShop and watch all your favourite movies and series</h1>
          <a href="./signUp/"> <button class="btn  rounded sign-btn">sign up <br><span class="material-symbols-outlined">movie</span><br> now </button></a>
        </div>
      </div>
      <div class="row second-compsant rounded">
        <div class="img-design-second col">
          <img src="./assets/images/second-image.svg" alt="">
          <h3 class="anim-desc text-capitalize fst-italic text-center">a whole library of movies and tv shows you'll never get bored with us </h3>
        </div>
        <div class="img-design-second col">
          <img src="./assets/images/first-image.svg" alt="">
          <h3 class="anim-desc text-capitalize fst-italic text-center">a whole stuff of employes here ready to help you ! </h3>
        </div>
        <div class="img-design-second col">
          <img src="./assets/images/third-image.svg" alt="">
          <h3 class="anim-desc last-one text-capitalize fst-italic text-center">HKmoviesShop is not all about movies here we build a base of people loving a whole culture</h3>
        </div>
      </div>
      <div class="row second-compsant rounded first-composant" style="margin-top: 12%;">
        <div class="col text-design">
          <h1 class="text-center text-bold text-break text-capitalize fst-italic">carrers</h1>
          <h3 class="text-center text-bold text-break text-capitalize fst-italic">are you looking for a job oppurtinity here we offer you a job apply now and become one of our wide family</h3>
          <a href="./applyjob/"> <button class="btn rounded sign-btn">apply for a job <br><span class="material-symbols-outlined">movie</span><br> now </button></a>
        </div>
        <div class="img-design-second col" style="margin-top: -2%;">
          <img src="./assets/images/job.svg" alt="">
        </div>
      </div>
    </div>
  </div>
  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">login</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <form method="POST" action="./login/">
            <div class="mb-3">
              <label for="email" class="form-label">Email address</label>
              <input type="email" class="form-control" id="email" name="email" aria-describedby="emailHelp">
            </div>
            <div class="mb-3">
              <label for="password" class="form-label">Password</label>
              <input type="password" class="form-control" id="password" name="password">
            </div>
            <button type="submit" class="btn" style="background-color: #BA68C8;" name="login">Submit</button>
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          </form>
        </div>
        <div class="modal-footer">
        </div>
      </div>
    </div>
  </div>
  <footer class="row mt-5">
    <div class="text-muted text-center text-light footer-insight">
      <div class="">
        <i class="bi bi-facebook"></i>
        <i class="bi bi-instagram"></i>
        <i class="bi bi-github"></i>
        <i class="bi bi-info-circle"></i>
      </div>
      <div class="second-footer">
        <p> &copy; 2022 made by Hkimi Mohamed Amin <i class="bi bi-linkedin"></i></p>
      </div>
    </div>
  </footer>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  <script src="./assets/script/script.js"></script>
</body>

</html>