<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>HKmoviesShop</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <link rel="stylesheet" href="../assets/style/style.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">
    <link rel="stylesheet" href="../assets/style/addings.css">
    <link rel="stylesheet" href="style.css">
    <style>
        .main {
            margin-top: 12% !important;
        }

        .submit-btn {
            background-color: #BA68C8;
            color: white;
        }

        .submit-btn:hover {
            background-color: #BA68C8;
            color: white;
        }

        .title {
            color: #BA68C8;
        }

        .main {
            height: 70vh;
        }
    </style>
</head>

<body>
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-margin background">
            <div class="container-fluid">
                <a class="navbar-brand" href="../layout.phtml"><img src="../assets/images/logoDark-removebg.png" alt="" class="logo"></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="../logout/"><span class="material-symbols-outlined text-white">
                                    home
                                </span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href=""><span class="material-symbols-outlined text-white">
                                    movie
                                </span></a>
                        </li>
                    </ul>
                    <div class="float-end d-flex info" style="margin-left: -12%;">
                        <div class="dropdown text-end">
                            <a href="
                            <?php if ($_SESSION['isAdmin'] == 1) {
                                echo '../admin/';
                            } else if ($_SESSION['isEmploye'] == 1) {
                                echo '../profile_employe/';
                            } else {
                                echo '../profile_user/';
                            }
                            ?>">
                                <img src="<?= $_SESSION['avatar'] ?>" alt="mdo" width="32" height="32" class="rounded-circle">
                            </a>
                            <!-- <ul class="dropdown-menu text-small">
                                <li><a class="dropdown-item" href="#">Settings</a></li>
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li><a class="dropdown-item" href="../logout/">Sign out</a></li>
                            </ul> -->
                        </div>
                        <p><?= $_SESSION['username'] ?></p>
                    </div>
                </div>
            </div>
        </nav>
        <div class="main">
        <div class="row">
                <?php if (array_key_exists('msg', $_GET)) : ?>
                    <div class="alert alert-<?= $_GET['class'] ?>">
                        <?= $_GET['msg']; ?>
                    </div>
                <?php endif; ?>
            </div>
            <div class="row shadow-lg rounded">
                <a href="index.php?filter=all" class="col"><button class="btn btn-bg" style="width: 100%;">ALL</button></a>
                <a href="index.php?filter=shows" class="col"><button class="btn btn-bg" style="width: 100%;">shows</button></a>
                <a href="index.php?filter=movies" class="col"><button class="btn btn-bg" style="width: 100%;">movies</button></a>
            </div>
            <?php if($filter=='all'|| $filter=='movies' ): ?>
            <h1 class="text-center">movies</h1>
            <div class="row">
                <?php foreach ($movies as $element) : ?>
                    <div class="image col">
                        <img class="image--img" src="<?= $element['poster'] ?> " height="300rem">
                        <div class="image--overplay">
                            <div class="image--description">
                                <p><?= $element['movie_name'] ?></p>
                                <p><?= $element['director'] ?></p>
                                <p><?= $element['descripition']?></p>
                                <p>length : <?= calculer_taille($element['length'])['nbheures'] . ':' . calculer_taille($element['length'])['nbminutes']  ?></p>
                                <p class="badge active"><?php donner_genre($element['idgenre'], $db); ?></p>
                                <div class="row">
                                    <a href="index.php?id_fav_movie=<?= $element['idmovie']?>" class="col">
                                        <button class="btn-poster <?= check_liked_movie($db,$element['idmovie']) ? 'btn-bg' : ''  ?>"><span class="material-symbols-outlined">
                                                    favorite
                                                </span></button></a>
                                    <a href="<?= $element['link']  ?>" class="col"><button class="btn-poster">
                                            <span class="material-symbols-outlined">
                                                play_arrow
                                            </span>
                                        </button>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                <?php endforeach ?>
            </div>
            <?php endif; ?>
            <br>
            <br>
            <?php if($filter=='all'|| $filter=='shows' ): ?>
            <h1 class="text-center">shows</h1>
            <div class="row">
                <?php foreach ($shows as $element) : ?>
                    <div class="image col">
                        <img class="image--img" src="<?= $element['poster'] ?> " height="300rem">
                        <div class="image--overplay">
                            <div class="image--description">
                                <p><?= $element['name'] ?></p>
                                <p><?= $element['director'] ?></p>
                                <p><?= $element['description']?></p>
                                <p class="badge active"><?php donner_genre($element['idgenre'], $db); ?></p>
                                <div class="row">
                                    <a href="index.php?id_fav_show=<?=$element['idtvshow']?>" class="col">
                                    <button class="btn-poster <?= check_liked_show($db,$element['idtvshow']) ? 'btn-bg' : ''  ?>"><span class="material-symbols-outlined"><span class="material-symbols-outlined">
                                                    favorite
                                                </span></span></button></a>
                                    <a href="<?= $element['link']  ?>" class="col"><button class="btn-poster">
                                            <span class="material-symbols-outlined">
                                                play_arrow
                                            </span>
                                        </button>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                <?php endforeach ?>
            </div>
            <?php endif; ?>
        </div>
        <footer class="row row-cols-1 row-cols-sm-2 row-cols-md-5 py-5 border-top" style="color: white;">
            <div class="col mb-3">
                <a href="/" class="d-flex align-items-center mb-3 link-dark text-decoration-none">
                    <img src="../assets/images/logoDark-removebg.png" width="100" height="100">
                </a>
            </div>
            <div class="col mb-3">
                <h5>Section</h5>
                <ul class="nav flex-column">
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-white">Home</a></li>
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-white">Features</a></li>
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-white">Pricing</a></li>
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-white">FAQs</a></li>
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-white">About</a></li>
                </ul>
            </div>
            <div class="col mb-3">
                <h5>Section</h5>
                <ul class="nav flex-column">
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-white">Home</a></li>
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-white">Features</a></li>
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-white">Pricing</a></li>
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-white">FAQs</a></li>
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-white">About</a></li>
                </ul>
            </div>
            <div class="col mb-3">
                <h5>socials</h5>
                <ul class="nav flex-column">
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-white"><i class="bi bi-facebook"></i></a></li>
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-white"> <i class="bi bi-instagram"></i></a></li>
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-white"> <i class="bi bi-github"></i></a></li>
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-white"><i class="bi bi-info-circle"></i></a></li>
                </ul>
            </div>
            <p class="text-muted">HKIMI MOHAMED AMIN &copy; 2022</p>
        </footer>
    </div>