<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>HKmoviesShop</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <link rel="stylesheet" href="../assets/style/style.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">
    <style>
      .frem {
            width: 100%;
            height: 100vh;
            display: flex;
            justify-content: center;
            align-items: center;
            flex-direction: column;
            background: url(../assets/images/gif.gif);
            background-position: center;
            background-repeat: no-repeat;
        }
        
        .frem p {
            position: absolute;
            top: 3rem;
            font-size: 7rem;
            color: #00000063;
        }
        
        .frem h2 {
            position: absolute;
            bottom: 8rem;
            font-size: 34px;
        }
        
        .frem h5 {
            position: absolute;
            bottom: 6rem;
            color: #9c9c9c;
        }
        
        .frem a {
            position: absolute;
            bottom: 1rem;
            background: linear-gradient(45deg, #ff0034, #ffbc00);
            padding: 12px;
            color: white;
            text-decoration: none;
            font-size: 23px;
            border-radius: 13px;
        }
    </style>
  </head>
<body>
  <?php if($verif==false){ ?>
    <div class="frem">
    <p>404</p>
    <h2>Look like you're lost</h2>
    <h5>the page you are looking for not available</h5>
    <a href="../layout.phtml">Go to Home</a>
</div>
    <?php }else{ ?>
<div class="container">
  <nav class="navbar navbar-expand-lg navbar-margin">
    <div class="container-fluid">
      <a class="navbar-brand" href="../layout.phtml"><img src="../assets/images/logoLight.png" alt="" class="logo"></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="../layout.phtml"><span class="material-symbols-outlined">
home
</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#"><span class="material-symbols-outlined">
movie
</span></a>
        </li>
        <li class="nav-item">
          <a href="#" class="nav-link"><span class="material-symbols-outlined">
badge
</span></a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          <span class="material-symbols-outlined">
manage_accounts
</span>
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#" data-bs-toggle="modal" data-bs-target="#exampleModal"><span class="material-symbols-outlined">
login
</span><span class="text-dropdown">login</span></a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href=""><span class="material-symbols-outlined">
person_add
</span><span class="text-dropdown">Sign Up</span></a></li>
            <li><hr class="dropdown-divider"></li>
          </ul>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
      </form>
    </div>
  </div>
</nav>
<div class="row">
    <div class="sign-up-user-form col">
<form class="shadow-lg p-5 rounded col"  method="POST" action="./index.php" enctype="multipart/form-data">
<h1 class="text-center text-capitalize">welcome fill this form and beacame one of our family</h1>
<?php if(array_key_exists('msg',$_GET)): ?>
            <div class="alert alert-<?=$_GET['class']?>">
                <?= $_GET['msg']; ?>
            </div>
    <?php endif; ?>
<div class="mb-3">
    <label for="username" class="form-label"> <i class="bi bi-person-circle"></i></label>
    <input type="text" class="form-control" id="username" name="username" placeholder="username" required>
</div>
<div class="mb-3">
    <label for="email" class="form-label"><i class="bi bi-envelope"></i></label>
    <input type="email" class="form-control" id="email" name="email" placeholder="Email address " required>
</div>
<div class="mb-3">
    <label for="password" class="form-label"> <i class="bi bi-lock-fill"></i></label>
    <input type="password" class="form-control" id="password" name="password" placeholder="Password" required>
</div>
<div class="mb-3">
    <label for="password2" class="form-label"> <i class="bi bi-lock-fill"></i></label>
    <input type="password" class="form-control" id="password2" name="password2" placeholder="confirm Password" required>
</div>
<div class="mb-3">
    <label for="avatar" class="form-label"><i class="bi bi-camera-fill" required></i></label>
    <input type="file" class="form-control" id="avatar" name="avatar">
</div>
    <button type="submit" class="btn btn-primary" name="submit">sign up</button>
</form>
    </div>
<div class="col">
<img src="../assets/images/job.svg" class="img-thumbnail logo">
</div>
</div>
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">login</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
      <form action="" method="POST">
  <div class="mb-3">
    <label for="email" class="form-label">Email address</label>
    <input type="email" class="form-control" id="email" name="email" aria-describedby="emailHelp">
  </div>
  <div class="mb-3">
    <label for="password" class="form-label">Password</label>
    <input type="password" class="form-control" id="password" name="password">
  </div>
  <button type="submit" class="btn" style="background-color: #BA68C8;">Submit</button>
  <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
</form>
      </div>
      <div class="modal-footer">
      </div>
    </div>
  </div>
</div>
</div>
<footer class="row mt-5">
    <div class="text-muted text-center text-light footer-insight">
      <div class="">
        <i class="bi bi-facebook"></i>
        <i class="bi bi-instagram"></i>
        <i class="bi bi-github"></i>
        <i class="bi bi-info-circle"></i>
      </div>
      <div class="second-footer">
        <p> &copy; 2022 made by Hkimi Mohamed Amin <i class="bi bi-linkedin"></i></p>
      </div>
    </div>
  </footer>
<?php } ?>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
<script src="../assets/script/script.js"></script>
</body>
</html>