<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>HKmoviesShop</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <link rel="stylesheet" href="../assets/style/style.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">
</head>

<body>
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-margin">
            <div class="container-fluid">
                <a class="navbar-brand" href="../layout.phtml"><img src="../assets/images/logoLight.png" alt="" class="logo"></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="../layout.phtml"><span class="material-symbols-outlined">
                                    home
                                </span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#"><span class="material-symbols-outlined">
                                    movie
                                </span></a>
                        </li>
                        <li class="nav-item">
                            <a href="#" class="nav-link"><span class="material-symbols-outlined">
                                    badge
                                </span></a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                <span class="material-symbols-outlined">
                                    manage_accounts
                                </span>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="#" data-bs-toggle="modal" data-bs-target="#exampleModal"><span class="material-symbols-outlined">
                                            login
                                        </span><span class="text-dropdown">login</span></a></li>
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li><a class="dropdown-item" href=""><span class="material-symbols-outlined">
                                            person_add
                                        </span><span class="text-dropdown">Sign Up</span></a></li>
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                            </ul>
                        </li>
                    </ul>
                    <div class="float-end d-flex">
                        <p><?= $_SESSION['username'] ?></p>
                        <img class="rounded shadow-sm" width="10%" height="10%" src="<?= $_SESSION['avatar'] ?>" alt="">
                        <a href="../logout/"><button class="btn btn-primary">logout</button></a>
                    </div>
                </div>
            </div>
        </nav>

    <div class="main">
    <div class="row">
        <h1 class="text-center">job demandes</h1>
        <?php foreach($res as $element){ ?>
                        <div class="demande card col">
                            <h3>name : <?=$element['name'] ?></h3>
                            <h3>email :  <?=$element['email'] ?></h3>
                            <h3>experince :  <?=$element['experience']==1 ? 'yes' : 'no' ?></h3>
                            <h5>state :  <?php 
                                if($element['state']==0){
                                    echo 'en cours';
                                }
                                else if($element['state']==1){
                                    echo 'accepted';
                                }else{
                                    echo 'not accepted ';
                                }?></h5>
                                <div class="d-flex">
                            <a href=".<?= $element['cv'] ?>" download="cv<?= $element['name'] ?>"><button class="btn btn-primary">download cv</button></a>
                            <a href="./index.php?id_apply=<?= $element['iddemande'] ?>&accept=1"><button <?= $element['state']!=0 ? 'disabled' : '' ?> class="btn btn-success">accept apply</button></a>
                            <a  href="./index.php?id_apply=<?= $element['iddemande'] ?>&refuse=1"><button <?= $element['state']!=0 ? 'disabled' : '' ?> class="btn btn-danger">refuse </button></a>
                            </div>
                        </div>
                        <?php }?>
    </div>
    </div>
    </div>
        <footer>
            <div class="text-muted text-center text-light footer-insight">
                <div class="">
                    <i class="bi bi-facebook"></i>
                    <i class="bi bi-instagram"></i>
                    <i class="bi bi-github"></i>
                    <i class="bi bi-linkedin"></i>
                </div>
                <div class="second-footer">
                    <p> &copy; 2022 made by Hkimi Mohamed Amin <i class="bi bi-info-circle"></i></p>
                </div>
            </div>
        </footer>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
        <script src="../assets/script/script.js"></script>

</body>

</html>