<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>HKmoviesShop</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <link rel="stylesheet" href="../assets/style/style.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">
    <link rel="stylesheet" href="../assets/style/addings.css">
    <link rel="stylesheet" href="style.css">
</head>

<body>
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-margin background">
            <div class="container-fluid">
                <a class="navbar-brand" href="../layout.phtml"><img src="../assets/images/logoDark-removebg.png" alt="" class="logo"></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page"  href="../logout/"><span class="material-symbols-outlined text-white">
                                    home
                                </span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="../movies_page/"><span class="material-symbols-outlined text-white">
                                    movie
                                </span></a>
                        </li>
                    </ul>
                    <div class="float-end d-flex info" style="margin-left: -12%;">
                        <div class="dropdown text-end">
                            <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                                <img src="<?= $_SESSION['avatar'] ?>" alt="mdo" width="32" height="32" class="rounded-circle">
                            </a>
                            <ul class="dropdown-menu text-small">
                                <li><a class="dropdown-item" href="../edit_user/index.php?edit_info=<?= $_SESSION['iduser'] ?>">Settings</a></li>
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li><a class="dropdown-item" href="../logout/">Sign out</a></li>
                            </ul>
                        </div>
                        <p><?= $_SESSION['username'] ?></p>
                    </div>
                </div>
            </div>
        </nav>
        <div class="main">
            <div class="d-flex align-items-start">
                <div class="nav flex-column nav-pills me-3" id="v-pills-tab" role="tablist" aria-orientation="vertical">
                    <button class="nav-link active" id="v-pills-home-tab" data-bs-toggle="pill" data-bs-target="#v-pills-home" type="button" role="tab" aria-controls="v-pills-home" aria-selected="true"><span class="material-symbols-outlined">
                            grid_view
                        </span></button>
                    <button class="nav-link" id="v-pills-profile-tab" data-bs-toggle="pill" data-bs-target="#v-pills-profile" type="button" role="tab" aria-controls="v-pills-profile" aria-selected="false"><span class="material-symbols-outlined">
                            pending
                        </span></button>
                    <button class="nav-link" id="v-pills-messages-tab" data-bs-toggle="pill" data-bs-target="#v-pills-messages" type="button" role="tab" aria-controls="v-pills-messages" aria-selected="false"><span class="material-symbols-outlined">
                            delete
                        </span></button>
                    <button class="nav-link" id="v-pills-employes-tab" data-bs-toggle="pill" data-bs-target="#v-pills-employes" type="button" role="tab" aria-controls="v-pills-employes" aria-selected="false"><span class="material-symbols-outlined">
                            badge
                        </span></button>
                    <button class="nav-link" id="v-pills-movies-tab" data-bs-toggle="pill" data-bs-target="#v-pills-movies" type="button" role="tab" aria-controls="v-pills-movies" aria-selected="false"><span class="material-symbols-outlined">
                            videocam
                        </span></button>
                    <button class="nav-link" id="v-pills-shows-tab" data-bs-toggle="pill" data-bs-target="#v-pills-shows" type="button" role="tab" aria-controls="v-pills-shows" aria-selected="false"><span class="material-symbols-outlined">
                            live_tv
                        </span></button>
                </div>
                <div class="tab-content" id="v-pills-tabContent">
                    <div class="tab-pane fade show active tab-bg" id="v-pills-home" role="tabpanel" aria-labelledby="v-pills-home-tab" tabindex="0">
                        <div class="insights row">
                            <div class="sales col">
                                <span class="material-symbols-outlined">
                                    movie
                                </span>
                                <div class="middle">
                                    <div class="left">
                                        <h3>number of movies and shows</h3>
                                        <h1><?= products_number($db) ?></h1>
                                    </div>
                                    <div class="progress">
                                        <svg>
                                            <circle cx="38" cy="38" r="36"></circle>
                                        </svg>
                                        <div class="number">
                                            <p>50%</p>
                                        </div>
                                    </div>
                                </div>
                                <small class="text-muted">all time</small>
                            </div>
                            <div class="expenses col">
                                <span class=" material-symbols-outlined ">
                                    person
                                </span>
                                <div class="middle ">
                                    <div class="left ">
                                        <h3>number of users</h3>
                                        <h1><?= total_users($db) ?></h1>
                                    </div>
                                    <div class="progress ">
                                        <svg>
                                            <circle cx="38 " cy="38 " r="36 "></circle>
                                        </svg>
                                        <div class="number ">
                                            <p>62%</p>
                                        </div>
                                    </div>
                                </div>
                                <small class="text-muted">all time</small>
                            </div>
                            <div class="income col">
                                <span class="material-symbols-outlined">
                                    work
                                </span>
                                <div class="middle ">
                                    <div class="left ">
                                        <h3>number of employees</h3>
                                        <h1><?= total_employes($db) ?></h1>
                                    </div>
                                    <div class="progress ">
                                        <svg>
                                            <circle cx="38 " cy="38 " r="36 "></circle>
                                        </svg>
                                        <div class="number ">
                                            <p>15%</p>
                                        </div>
                                    </div>
                                </div>
                                <small class="text-muted">all time</small>
                            </div>
                            <div class="income col">
                                <span class="material-symbols-outlined">
                                    movie
                                </span>
                                <div class="middle ">
                                    <div class="left ">
                                        <h3>number of shows</h3>
                                        <h1><?= shows_number($db) ?></h1>
                                    </div>
                                    <div class="progress ">
                                        <svg>
                                            <circle cx="38 " cy="38 " r="36 "></circle>
                                        </svg>
                                        <div class="number ">
                                            <p>15%</p>
                                        </div>
                                    </div>
                                </div>
                                <small class="text-muted">all time</small>
                            </div>
                            <div class="income col">
                                <span class="material-symbols-outlined">
                                    movie
                                </span>
                                <div class="middle ">
                                    <div class="left ">
                                        <h3>number of movies</h3>
                                        <h1><?= total_employes($db) ?></h1>
                                    </div>
                                    <div class="progress ">
                                        <svg>
                                            <circle cx="38 " cy="38 " r="36 "></circle>
                                        </svg>
                                        <div class="number ">
                                            <p>15%</p>
                                        </div>
                                    </div>
                                </div>
                                <small class="text-muted">all time</small>
                            </div>
                        </div>
                    </div>
                    <div class="tab-pane fade tab-bg" id="v-pills-profile" role="tabpanel" aria-labelledby="v-pills-profile-tab" tabindex="0">
                        <table>
                            <thead>
                                <th>name</th>
                                <th>email</th>
                                <th>experience</th>
                                <th>cv</th>
                                <th>details </th>
                                <th>state</th>
                                <th>operation</th>
                            </thead>
                            <tbody>
                                <?php foreach ($pending as $element) { ?>
                                    <tr>
                                        <td><?= $element['name'] ?></td>
                                        <td><a href="mailto:<?= $element['email'] ?>"><?= $element['email'] ?></a></td>
                                        <td><?= $element['experience'] == 1 ? 'yes' : 'no' ?></td>
                                        <td><a href=".<?= $element['cv'] ?>" download="<?= $element['name'] ?>" class="btn active"><span class="material-symbols-outlined" style="color: white;">
                                                    download
                                                </span></a></td>
                                        <td class="primary"><button class="btn active" data-bs-toggle="modal" data-bs-target="#exampleModal"><span class="material-symbols-outlined" style="color: white;">
                                                    visibility
                                                </span></button></td>
                                        <td class="primary"><span class="badge active">pending</span></td>
                                        <td class="primary">
                                            <a href="./index.php?id_apply=<?= $element['iddemande'] ?>&accept=1"><button <?= $element['state'] != 0 ? 'disabled' : '' ?> class="btn btn-success"><span class="material-symbols-outlined">done_all</span></button></a>
                                            <a href="./index.php?id_apply=<?= $element['iddemande'] ?>&refuse=1"><button <?= $element['state'] != 0 ? 'disabled' : '' ?> class="btn btn-danger"><span class="material-symbols-outlined">
                                                        block
                                                    </span></button></a>
                                        </td>
                                        <td>
                                        </td>
                                        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                            <div class="modal-dialog">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <h1 class="modal-title fs-5 text-center" id="exampleModalLabel">job demandes</h1>
                                                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                                    </div>
                                                    <div class="modal-body">
                                                        <?= $element['description']; ?>
                                                    </div>
                                                    <div class="modal-footer">
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </tr>
                                <?php } ?>
                            </tbody>
                        </table>
                    </div>
                    <div class="tab-pane fade tab-bg" id="v-pills-messages" role="tabpanel" aria-labelledby="v-pills-messages-tab" tabindex="0">
                        <table>
                            <thead>
                                <th>name</th>
                                <th>email</th>
                                <th>experience</th>
                                <th>cv</th>
                                <th>details </th>
                                <th>state</th>
                            </thead>
                            <tbody>
                                <?php foreach ($declined as $element) { ?>
                                    <tr>
                                        <td><?= $element['name'] ?></td>
                                        <td><a href="mailto:<?= $element['email'] ?>"><?= $element['email'] ?></a></td>
                                        <td><?= $element['experience'] == 1 ? 'yes' : 'no' ?></td>
                                        <td><a href=".<?= $element['cv'] ?>" download="<?= $element['name'] ?>" class="btn active"><span class="material-symbols-outlined" style="color: white;">
                                                    download
                                                </span></a></td>
                                        <td class="primary"><button class="btn active" data-bs-toggle="modal" data-bs-target="#declined"><span class="material-symbols-outlined" style="color: white;">
                                                    visibility
                                                </span></button></td>
                                        <td class="primary"><span class="badge active">declined</span></td>
                                        <td>
                                        </td>
                                        <div class="modal fade" id="declined" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                            <div class="modal-dialog">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <h1 class="modal-title fs-5 text-center" id="declined">declined requests</h1>
                                                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                                    </div>
                                                    <div class="modal-body">
                                                        <?= $element['description']; ?>
                                                    </div>
                                                    <div class="modal-footer">
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </tr>
                                <?php } ?>
                            </tbody>
                        </table>
                    </div>
                    <div class="tab-pane fade tab-bg" id="v-pills-employes" role="tabpanel" aria-labelledby="v-pills-employes-tab" tabindex="0">
                        <div class="row">
                            <?php foreach ($employes as $element) { ?>
                                <div class="card mb-3 col">
                                    <div class="row g-0">
                                        <div class="col-md-4">
                                            <img src="<?= $element['avatar'] ?>" class="img-fluid rounded-start" alt="employe image" />
                                        </div>
                                        <div class="col-md-8">
                                            <div class="card-body">
                                                <h5 class="card-title"><?= $element['username'] ?></h5>
                                                <p class="card-text">
                                                <p class="fw-light"><a href="<?= $element['email'] ?>"><?= $element['email'] ?></a></p>
                                                <p class="text-muted">working since : <?= $element['createdate'] ?></p>
                                                </p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            <?php } ?>
                        </div>
                    </div>
                    <div class="tab-pane fade tab-bg" id="v-pills-movies" role="tabpanel" aria-labelledby="v-pills-movies-tab" tabindex="0">
                    <div class="row">
                            <h1 class="text-center">Added movies</h1>
                            <?php foreach ($liked_movies as $element) : ?>
                                <div class="image col">
                                    <img class="image--img" src="<?= $element['poster'] ?> " height="300rem">
                                    <div class="image--overplay">
                                        <div class="image--description">
                                            <p><?= $element['movie_name'] ?></p>
                                            <p><?= $element['director'] ?></p>
                                            <p>length : <?= calculer_taille($element['length'])['nbheures'] . ':' . calculer_taille($element['length'])['nbminutes']  ?></p>
                                            <p class="badge active"><?php donner_genre($element['idgenre'], $db); ?></p>
                                            <div class="row">
                                                <a href="index.php?id_forever_movie=<?= $element['idmovie'] ?>" class="col">
                                                    <button class="btn-poster"><span class="material-symbols-outlined">delete</span></button>
                                                </a>
                                                <a href="<?= $element['link']  ?>" class="col"><button class="btn-poster">
                                                        <span class="material-symbols-outlined">
                                                            play_arrow
                                                        </span>
                                                    </button>
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            <?php endforeach; ?>
                        </div>
                        </div>
                    <div class="tab-pane fade tab-bg" id="v-pills-shows" role="tabpanel" aria-labelledby="v-pills-shows-tab" tabindex="0">
                        <div class="row">
                    <h1 class="text-center">liked Shows</h1>
                            <?php foreach ($liked_shows as $element) : ?>
                                <div class="image col">
                                    <img class="image--img" src="<?= $element['poster'] ?> " height="300rem">
                                    <div class="image--overplay">
                                        <div class="image--description">
                                            <p><?= $element['name'] ?></p>
                                            <p><?= $element['director'] ?></p>
                                            <p class="badge active"><?php donner_genre($element['idgenre'], $db); ?></p>
                                            <div class="row">
                                                <a href="index.php?id_forever_show=<?= $element['idtvshow'] ?>" class="col">
                                                    <button class="btn-poster"><span class="material-symbols-outlined">delete</span></button>
                                                </a>
                                                <a href="<?= $element['link']  ?>" class="col"><button class="btn-poster">
                                                        <span class="material-symbols-outlined">
                                                            play_arrow
                                                        </span>
                                                    </button>
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            <?php endforeach; ?>
                            </div>
                    </div>
                </div>
            </div>
        </div>
        <footer class="row row-cols-1 row-cols-sm-2 row-cols-md-5 py-5 border-top" style="color: white;">
            <div class="col mb-3">
                <a href="/" class="d-flex align-items-center mb-3 link-dark text-decoration-none">
                    <img src="../assets/images/logoDark-removebg.png" width="100" height="100">
                </a>
            </div>
            <div class="col mb-3">
            </div>
            <div class="col mb-3">
                <h5>Section</h5>
                <ul class="nav flex-column">
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-white">Home</a></li>
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-white">Features</a></li>
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-white">Pricing</a></li>
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-white">FAQs</a></li>
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-white">About</a></li>
                </ul>
            </div>
            <div class="col mb-3">
                <h5>Section</h5>
                <ul class="nav flex-column">
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-white">Home</a></li>
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-white">Features</a></li>
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-white">Pricing</a></li>
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-white">FAQs</a></li>
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-white">About</a></li>
                </ul>
            </div>
            <div class="col mb-3">
                <h5>socials</h5>
                <ul class="nav flex-column">
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-white"><i class="bi bi-facebook"></i></a></li>
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-white"> <i class="bi bi-instagram"></i></a></li>
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-white"> <i class="bi bi-github"></i></a></li>
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-white"><i class="bi bi-info-circle"></i></a></li>
                </ul>
            </div>
            <p class="text-muted">HKIMI MOHAMED AMIN &copy; 2022</p>
        </footer>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    <script src="../assets/script/script.js"></script>

</body>

</html>