<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>HKmoviesShop</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <link rel="stylesheet" href="../assets/style/style.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">
    <link rel="stylesheet" href="../assets/style/addings.css">
    <style>
        .main {
            margin-top: 8% !important;
        }

        .active {
            background-color: #BA68C8 !important;
        }

        .show {
            background-color: #fff !important;
        }

        .navlink {
            background-color: #fff !important;
        }

        .main {
            margin-left: -6% !important;
        }

        .main .insights>div {
            background: #fff;
            padding: 1.8rem;
            border-radius: 2rem;
            margin-top: 1rem;
            box-shadow: 0 2rem 3rem lightgray;
            transition: all 300ms ease;
        }
        .insights{
            gap: 10%;
        }
        .main .insights>div:hover {
            box-shadow: 0 1rem 2rem whitesmoke;
        }

        .main .insights>div span {
            background: #7380ec;
            padding: 0.5rem;
            border-radius: 50%;
            color: #fff;
            font-size: 2rem;
        }

        .main .insights>div.expenses span {
            background-color: #ff7782;
        }

        .main .insights>div.income span {
            background-color: #41f1b6;
        }

        .main .insights>div .middle {
            display: flex;
            align-items: center;
            justify-content: space-between;
        }

        .main .insights h3 {
            margin: 1rem 0 0.6rem;
            font-size: 1rem;
        }

        .main .insights .progress {
            position: relative;
            width: 92px;
            height: 92px;
            border-radius: 50%;
        }

        .main .insights svg {
            width: 7rem;
            height: 7rem;
        }

        .main .insights svg circle {
            fill: none;
            stroke: #7380ec;
            stroke-width: 14;
            stroke-linecap: round;
            transform: translate(5px, 5px);
            stroke-dasharray: 110;
            stroke-dashoffset: 92;
        }

        .main .insights .sales svg circle {
            stroke-dashoffset: -30;
            stroke-dasharray: 400;
        }

        .main .insights .expenses svg circle {
            stroke-dashoffset: 20;
            stroke-dasharray: 80;
        }

        .main .insights .income svg circle {
            stroke-dashoffset: 35;
            stroke-dasharray: 110;
        }

        .main .insights .progress .number {
            position: absolute;
            top: 0;
            left: 0;
            height: 100%;
            width: 100%;
            display: flex;
            justify-content: center;
            align-items: center;
            /*margin-left: 29px;*/
        }

        .main.insights small {
            margin-top: 1.3rem;
            display: block;
        }

        .tab-content {
            margin-left: 5% !important;
        }
        table {
    background: #fff;
    width: 100%;
    border-radius: 2rem;
    text-align: center;
    padding: 1.8rem;
    box-shadow: 0 2rem 3rem lightgrey;
    transition: all 300ms ease;
}
table tbody td {
    height: 2.8rem;
    border-bottom: 1px solid black;
    color: #677483;
}
table tbody tr:last-child td {
    border: none;
}
table {
        width: 83vw;
    }
    table thead tr th:last-child,
    table thead tr th:first-child {
        display: none;
    }
    table tbody tr td:last-child,
    table tbody tr td:first-child {
        display: none;
    }
    table {
        width: 100%;
        margin: 0;
    }
    </style>
</head>

<body>
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-margin background">
            <div class="container-fluid">
                <a class="navbar-brand" href="../layout.phtml"><img src="../assets/images/logoDark-removebg.png" alt="" class="logo"></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="../index.php"><span class="material-symbols-outlined text-white">
                                    home
                                </span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#"><span class="material-symbols-outlined text-white">
                                    movie
                                </span></a>
                        </li>
                        <li class="nav-item">
                            <a href="#" class="nav-link"><span class="material-symbols-outlined text-white">
                                    badge
                                </span></a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                <span class="material-symbols-outlined text-white">
                                    request_page
                                </span>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="#" data-bs-toggle="modal" data-bs-target="#exampleModal"><span class="material-symbols-outlined">
                                            pending
                                        </span><span class="text-dropdown">pending requests</span></a></li>
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li><a class="dropdown-item" href="" data-bs-toggle="modal" data-bs-target="#declined"><span class="material-symbols-outlined">
                                            delete
                                        </span><span class="text-dropdown">deleted demands</span></a></li>
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                            </ul>
                        </li>
                    </ul>
                    <div class="float-end d-flex info" style="margin-left: -12%;">
                        <p><?= $_SESSION['username'] ?></p>
                        <div class="dropdown text-end">
                            <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                                <img src="<?= $_SESSION['avatar'] ?>" alt="mdo" width="32" height="32" class="rounded-circle">
                            </a>
                            <ul class="dropdown-menu text-small">
                                <li><a class="dropdown-item" href="#">Settings</a></li>
                                <li><a class="dropdown-item" href="#">Profile</a></li>
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li><a class="dropdown-item" href="../logout/">Sign out</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </nav>
        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h1 class="modal-title fs-5 text-center" id="exampleModalLabel">job demandes</h1>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <?php foreach ($encours as $element) { ?>
                            <div class="demande card col">
                                <h3>name : <?= $element['name'] ?></h3>
                                <h3>email : <?= $element['email'] ?></h3>
                                <h3>experince : <?= $element['experience'] == 1 ? 'yes' : 'no' ?></h3>
                                <h5>state : <?php
                                            if ($element['state'] == 0) {
                                                echo 'en cours';
                                            } else if ($element['state'] == 1) {
                                                echo 'accepted';
                                            } else {
                                                echo 'not accepted ';
                                            } ?></h5>
                                <div class="d-flex">
                                    <a href="<?= $element['cv'] ?>" download="cv <?= $element['name'] ?>"><button class="btn btn-primary">download cv</button></a>
                                    <a href="./index.php?id_apply=<?= $element['iddemande'] ?>&accept=1"><button <?= $element['state'] != 0 ? 'disabled' : '' ?> class="btn btn-success">accept apply</button></a>
                                    <a href="./index.php?id_apply=<?= $element['iddemande'] ?>&refuse=1"><button <?= $element['state'] != 0 ? 'disabled' : '' ?> class="btn btn-danger">refuse </button></a>
                                </div>
                            </div>
                        <?php } ?>
                    </div>
                    <div class="modal-footer">
                    </div>
                </div>
            </div>
        </div>
        <div class="modal fade" id="declined" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h1 class="modal-title fs-5 text-center" id="exampleModalLabel">job demandes</h1>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <?php foreach ($declined as $element) { ?>
                            <div class="demande card col">
                                <h3>name : <?= $element['name'] ?></h3>
                                <h3>email : <?= $element['email'] ?></h3>
                                <h3>experince : <?= $element['experience'] == 1 ? 'yes' : 'no' ?></h3>
                                <h5>state : <?php
                                            if ($element['state'] == 0) {
                                                echo 'en cours';
                                            } else if ($element['state'] == 1) {
                                                echo 'accepted';
                                            } else {
                                                echo 'not accepted ';
                                            } ?></h5>
                                <div class="d-flex">
                                    <a href=".<?= $element['cv'] ?>" download="cv <?= $element['name'] ?>"><button class="btn btn-primary">download cv</button></a>
                                    <a href="./index.php?id_apply=<?= $element['iddemande'] ?>&accept=1"><button <?= $element['state'] != 0 ? 'disabled' : '' ?> class="btn btn-success">accept apply</button></a>
                                    <a href="./index.php?id_apply=<?= $element['iddemande'] ?>&refuse=1"><button <?= $element['state'] != 0 ? 'disabled' : '' ?> class="btn btn-danger">refuse </button></a>
                                </div>
                            </div>
                        <?php } ?>
                    </div>
                    <div class="modal-footer">
                    </div>
                </div>
            </div>
        </div>
        <div class="main">
            <div class="d-flex align-items-start">
                <div class="nav flex-column nav-pills me-3" id="v-pills-tab" role="tablist" aria-orientation="vertical">
                    <button class="nav-link active" id="v-pills-home-tab" data-bs-toggle="pill" data-bs-target="#v-pills-home" type="button" role="tab" aria-controls="v-pills-home" aria-selected="true"><span class="material-symbols-outlined">
                            grid_view
                        </span></button>
                    <button class="nav-link" id="v-pills-profile-tab" data-bs-toggle="pill" data-bs-target="#v-pills-profile" type="button" role="tab" aria-controls="v-pills-profile" aria-selected="false"><span class="material-symbols-outlined">
                            badge
                        </span></button>
                    <button class="nav-link" id="v-pills-messages-tab" data-bs-toggle="pill" data-bs-target="#v-pills-messages" type="button" role="tab" aria-controls="v-pills-messages" aria-selected="false"><span class="material-symbols-outlined">
                            query_stats
                        </span></button>
                </div>
                <div class="tab-content" id="v-pills-tabContent">
                    <div class="tab-pane fade show active" id="v-pills-home" role="tabpanel" aria-labelledby="v-pills-home-tab" tabindex="0">
                        <div class="insights row">
                            <div class="sales col">
                                <span class="material-symbols-outlined">
                                    movie
                                </span>
                                <div class="middle">
                                    <div class="left">
                                        <h3>number of movies and shows</h3>
                                        <h1><?= products_number($db) ?></h1>
                                    </div>
                                    <div class="progress">
                                        <svg>
                                            <circle cx="38" cy="38" r="36"></circle>
                                        </svg>
                                        <div class="number">
                                            <p>50%</p>
                                        </div>
                                    </div>
                                </div>
                                <small class="text-muted">all time</small>
                            </div>
                            <div class="expenses col">
                                <span class=" material-symbols-outlined ">
                                    person
                                </span>
                                <div class="middle ">
                                    <div class="left ">
                                        <h3>number of users</h3>
                                        <h1><?= total_users($db) ?></h1>
                                    </div>
                                    <div class="progress ">
                                        <svg>
                                            <circle cx="38 " cy="38 " r="36 "></circle>
                                        </svg>
                                        <div class="number ">
                                            <p>62%</p>
                                        </div>
                                    </div>
                                </div>
                                <small class="text-muted">all time</small>
                            </div>
                            <div class="income col">
                                <span class="material-symbols-outlined">
                                    work
                                </span>
                                <div class="middle ">
                                    <div class="left ">
                                        <h3>number of employees</h3>
                                        <h1><?= total_employes($db) ?></h1>
                                    </div>
                                    <div class="progress ">
                                        <svg>
                                            <circle cx="38 " cy="38 " r="36 "></circle>
                                        </svg>
                                        <div class="number ">
                                            <p>15%</p>
                                        </div>
                                    </div>
                                </div>
                                <small class="text-muted">all time</small>
                            </div>
                            <div class="income col">
                                <span class="material-symbols-outlined">
                                    movie
                                </span>
                                <div class="middle ">
                                    <div class="left ">
                                        <h3>number of shows</h3>
                                        <h1><?= shows_number($db) ?></h1>
                                    </div>
                                    <div class="progress ">
                                        <svg>
                                            <circle cx="38 " cy="38 " r="36 "></circle>
                                        </svg>
                                        <div class="number ">
                                            <p>15%</p>
                                        </div>
                                    </div>
                                </div>
                                <small class="text-muted">all time</small>
                            </div>
                            <div class="income col">
                                <span class="material-symbols-outlined">
                                    movie
                                </span>
                                <div class="middle ">
                                    <div class="left ">
                                        <h3>number of movies</h3>
                                        <h1><?= total_employes($db) ?></h1>
                                    </div>
                                    <div class="progress ">
                                        <svg>
                                            <circle cx="38 " cy="38 " r="36 "></circle>
                                        </svg>
                                        <div class="number ">
                                            <p>15%</p>
                                        </div>
                                    </div>
                                </div>
                                <small class="text-muted">all time</small>
                            </div>
                        </div>
                    </div>
                    <div class="tab-pane fade" id="v-pills-profile" role="tabpanel" aria-labelledby="v-pills-profile-tab" tabindex="0">
                    <table>
                    <thead>
                        <th>name</th>
                        <th>email</th>
                        <th>experience</th>
                        <th>cv </th>
                        <th>details </th>
                    </thead>
                    <tbody>
                        <?php foreach($employes as $element){ ?>
                        <tr>
                            <td>code it up 2.0</td>
                            <td>8000$</td>
                            <td>Due</td>
                            <td class="warning">pending</td>
                            <td class="primary">aaa</td>
                        </tr>
                        <?php } ?>
                    </tbody>
                </table>
                    </div>
                    <div class="tab-pane fade" id="v-pills-messages" role="tabpanel" aria-labelledby="v-pills-messages-tab" tabindex="0">...</div>
                </div>
            </div>
        </div>

        <footer class="row row-cols-1 row-cols-sm-2 row-cols-md-5 py-5 border-top" style="color: white;">
            <div class="col mb-3">
                <a href="/" class="d-flex align-items-center mb-3 link-dark text-decoration-none">
                    <img src="../assets/images/logoDark-removebg.png" width="100" height="100">
                </a>
            </div>

            <div class="col mb-3">

            </div>

            <div class="col mb-3">
                <h5>Section</h5>
                <ul class="nav flex-column">
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-white">Home</a></li>
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-white">Features</a></li>
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-white">Pricing</a></li>
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-white">FAQs</a></li>
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-white">About</a></li>
                </ul>
            </div>
            <div class="col mb-3">
                <h5>Section</h5>
                <ul class="nav flex-column">
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-white">Home</a></li>
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-white">Features</a></li>
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-white">Pricing</a></li>
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-white">FAQs</a></li>
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-white">About</a></li>
                </ul>
            </div>
            <div class="col mb-3">
                <h5>socials</h5>
                <ul class="nav flex-column">
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-white"><i class="bi bi-facebook"></i></a></li>
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-white"> <i class="bi bi-instagram"></i></a></li>
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-white"> <i class="bi bi-github"></i></a></li>
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-white"><i class="bi bi-info-circle"></i></a></li>
                </ul>
            </div>
            <p class="text-muted">HKIMI MOHAMED AMIN &copy; 2022</p>
        </footer>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    <script src="../assets/script/script.js"></script>

</body>

</html>