<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>verification page</title>
</head>
<body>
        <div>
            <?php if($resultats==1){?>
                <h1 class="text-center text-success">you are aleady verified</h1>
            <?php }else if($resultats==3){?>
                <h1 class="text-center text-success">you account has been verified succesfuly</h1>
            <?php }else{ ?>
                <h1 class="text-center text-danger">there been a problem ! please try again later !</h1>
                <?php } ?>
        </div>
</body>
</html>